### PR TITLE
Fix crush when sending more than one parameter with null value

### PR DESCRIPTION
**Pull request by kuosman**
Hi,
this fix JSChannel error when sending more than one parameter with null values.
## 

Marko

### CODE REVIEW

**Comment by yochannah** [comment]
Hey, this looks awesome and a completely reasonable thing to add. Can you add details on how to reproduce the bug so I can test it before I merge the PR?

Thanks!!

**Comment by kuosman** [comment]
Hey,

We use it like this:
var geojsonObject = {
       'type': 'FeatureCollection',
       'crs': {
         'type': 'name',
         'properties': {
           'name': 'EPSG:3067'
         }
       },
       'features': [
         {
           'type': 'Feature',
           'geometry': {
             'type': 'Polygon',
             'coordinates': [[[323424,6828464],[324192,6825872],[323744,6822384],[323424,6828464]]]
           },
           'properties': {
               'test_property': '123-456-7777-8888',
               'species': 'parcel'
           }
         },
         {
             'type': 'Feature',
             'geometry': {
               'type': 'Polygon',
               'coordinates': [[[309856,6829840],[312576,6833808],[315424,6831120],[315040,6828592],[311328,6827472],[309856,6829840]]]
             }  
         }  
       ]
};  
var params = [geojsonObject, {
        layerId: 'testLayer', 
        clearPrevious: false,
        centerTo: true,
        featureStyle: {
            fill: {
                color: 'rgba(255,0,255,0.2)'
            },
            stroke : {
                color: null,
                width: 3
            },
            text : {
                scale : null,
                fill : {
                    color : 'rgba(0,0,0,1)'
                },
                stroke : {
                    color : 'rgba(255,255,255,1)',
                    width : 2
                },
                labelProperty: 'test_property'
            }
        },
        cursor: 'zoom-out',
        prio: 1
}];

channel.call({
    method: 'postRequest',
    params: ['MapModulePlugin.AddFeaturesToMapRequest', params],
    success: function (v) { console.log(v); },
    error: function (v) { console.log(v); }
});

This call crush because of there are two null values in object (params-->featureStyle-->stroke-->color and  params-->featureStyle-->text-->scale).

## 

Marko

**Comment by XVincentX** [comment]
@yochannah Any update?

**Comment by ZakarFin** [comment]
We needed the fix asap and have a fork with this change here https://github.com/nls-oskari/jschannel/tree/v1.0.1

For npm you can use something like this https://github.com/nls-oskari/rpc-client/blob/master/package.json#L27

**Comment by yochannah** [comment]
Crap, I'm sorry for forgetting this. I'll release it now. 2 mins

**Comment by yochannah** [comment]
here you go kids, version 1.0.1
https://www.npmjs.com/package/jschannel

**Comment by yochannah** [comment]
in the future feel free to poke me if I don't respond after a day or so, but I'll try not to arbitrarily forget about PRs for ages in the future 😞

**Comment by XVincentX** [comment]
Thanks for being so responsive!

**Pull request merged**
