### PR TITLE
Let people risk and communicate in the same window

### PR DESCRIPTION
**Pull request by XVincentX**
I've been testing and using this for a while and I really do not see any reason why this would not work when used in the same window.

Probably the browser as of today changed. I'd give it a try!

### CODE REVIEW

**Comment by XVincentX** [comment]
@yochannah Ping!

**Comment by yochannah** [comment]
@XVincentX  Thanks for the ping!

https://www.npmjs.com/package/jschannel 1.0.2 on npm now.

**Comment by yochannah** [comment]
@XVincentX I don't actually use this package any more. Would you like me to add you as an owner on this repo and npm?

**Comment by XVincentX** [comment]
As I am actively working on it I'd be delighted to take over!

**Comment by yochannah** [comment]
woot woot! I'll add you on npm using this guide: https://docs.npmjs.com/cli/owner - let me know your npm username?

**Comment by XVincentX** [comment]
It's `vincenzo`

**Comment by yochannah** [comment]
you should have full access on npm now I think. Feel free to kick me off if you wish once you're sure you have everything you need!

**Comment by XVincentX** [comment]
Thanks a lot. Everything seems to be set.

**Pull request merged**
